export const SIMPLE_LASER_COST = 10
export const AUTO_FIRE_COST = 250
export const AUTO_FIRE_SPEED_MULTIPLIER = 1.6
export const BASE_MANUAL_FIRE_COOLDOWN = 0.15

export const LASER_BASE_FREQUENCY = 0.005
export const LASER_BASE_AMPLITUDE = 50
export const LASER_BASE_WIDTH = 3
export const MAX_LASER_WIDTH = 12
export const LASER_BASE_FIRE_RATE = 4
export const PLASMA_UNLOCK_POINTS = 1000
export const PLASMA_FREQUENCY_MULTIPLIER = 1.4
export const PLASMA_AMPLITUDE_MULTIPLIER = 1.25
export const PLASMA_WIDTH_MULTIPLIER = 1.6
export const PLASMA_FIRE_RATE_MULTIPLIER = 1.1

export const TARGET_BASE_SPAWN_RATE = 1
export const TARGET_VALUE_BASE = 1
export const TARGET_VALUE_GROWTH = 1.15
export const TARGET_ARMORED_CHANCE = 0.06
export const TARGET_HIGH_VALUE_CHANCE = 0.10
export const TARGET_ARMORED_VALUE_MULTIPLIER = 3
export const TARGET_HIGH_VALUE_VALUE_MULTIPLIER = 4
export const TARGET_ARMORED_HEALTH = 3
export const TARGET_REINFORCED_UNLOCK_LEVEL = 1
export const TARGET_REINFORCED_CHANCE = 0.04
export const TARGET_REINFORCED_VALUE_MULTIPLIER = 7
export const TARGET_REINFORCED_HEALTH = 6
export const TARGET_REINFORCED_RADIUS = 22
export const MAX_ACTIVE_TARGETS = 120

export const UPGRADE_GROWTH = 1.35

export const FREQUENCY_UPGRADE_BASE = 10
export const AMPLITUDE_UPGRADE_BASE = 15
export const FIRERATE_UPGRADE_BASE = 20
export const TARGET_VALUE_UPGRADE_BASE = 35
export const TARGET_SPAWN_RATE_UPGRADE_BASE = 45
export const TARGET_DIVERSITY_UPGRADE_BASE = 60

export const FREQUENCY_UPGRADE_STEP = 0.0006
export const FREQUENCY_UPGRADE_AMPLITUDE_BONUS = 2
export const FREQUENCY_UPGRADE_WIDTH_BONUS = 0.15
export const AMPLITUDE_UPGRADE_STEP = 8
export const FIRERATE_UPGRADE_STEP = 0.5
export const TARGET_VALUE_UPGRADE_STEP = 0.10
export const TARGET_SPAWN_RATE_UPGRADE_STEP = 0.15
