import {
    LASER_BASE_FREQUENCY,
    LASER_BASE_AMPLITUDE,
    LASER_BASE_WIDTH,
    LASER_BASE_FIRE_RATE,
    PLASMA_FREQUENCY_MULTIPLIER,
    PLASMA_AMPLITUDE_MULTIPLIER,
    PLASMA_WIDTH_MULTIPLIER,
    PLASMA_FIRE_RATE_MULTIPLIER
} from "./constants.js"

export const LASER_TYPES = {
    simple: {
        id: "simple",
        name: "Simple Laser",
        frequency: LASER_BASE_FREQUENCY,
        amplitude: LASER_BASE_AMPLITUDE,
        width: LASER_BASE_WIDTH,
        fireRate: LASER_BASE_FIRE_RATE,
        strength: 1,
        color: "#3a5cff",
        baseFrequency: LASER_BASE_FREQUENCY,
        baseAmplitude: LASER_BASE_AMPLITUDE,
        baseWidth: LASER_BASE_WIDTH,
        baseFireRate: LASER_BASE_FIRE_RATE,
        baseStrength: 1,
        colors: ["#3a5cff", "#7b3aff", "#00aaff", "#6a00ff"],
        glowMultiplier: 1.0,
        flashMultiplier: 1.0
    },
    plasma: {
        id: "plasma",
        name: "Plasma Laser",
        frequency: LASER_BASE_FREQUENCY * PLASMA_FREQUENCY_MULTIPLIER,
        amplitude: LASER_BASE_AMPLITUDE * PLASMA_AMPLITUDE_MULTIPLIER,
        width: LASER_BASE_WIDTH * PLASMA_WIDTH_MULTIPLIER,
        fireRate: LASER_BASE_FIRE_RATE * PLASMA_FIRE_RATE_MULTIPLIER,
        strength: 2,
        color: "#ff7a00",
        baseFrequency: LASER_BASE_FREQUENCY * PLASMA_FREQUENCY_MULTIPLIER,
        baseAmplitude: LASER_BASE_AMPLITUDE * PLASMA_AMPLITUDE_MULTIPLIER,
        baseWidth: LASER_BASE_WIDTH * PLASMA_WIDTH_MULTIPLIER,
        baseFireRate: LASER_BASE_FIRE_RATE * PLASMA_FIRE_RATE_MULTIPLIER,
        baseStrength: 2,
        colors: ["#ff7a00", "#ffb347", "#ff4d4d", "#ffcc33"],
        glowMultiplier: 1.8,
        flashMultiplier: 1.4
    },
    pulse: {
        id: "pulse",
        name: "Pulse Laser",
        frequency: 0.0054,
        amplitude: 34,
        width: 4,
        fireRate: 1.25,
        strength: 2,
        color: "#66f3ff",
        baseFrequency: 0.0054,
        baseAmplitude: 34,
        baseWidth: 4,
        baseFireRate: 1.25,
        baseStrength: 2,
        colors: ["#66f3ff", "#5aa9ff", "#7fffd4", "#b0f5ff"],
        glowMultiplier: 1.6,
        flashMultiplier: 1.2
    },
    scatter: {
        id: "scatter",
        name: "Scatter Laser",
        frequency: 0.0062,
        amplitude: 42,
        width: 2.6,
        fireRate: 1.1,
        strength: 1.5,
        color: "#ffcf66",
        baseFrequency: 0.0062,
        baseAmplitude: 42,
        baseWidth: 2.6,
        baseFireRate: 1.1,
        baseStrength: 1.5,
        colors: ["#ffcf66", "#ff9d66", "#ffdcb0", "#ffc76b"],
        glowMultiplier: 1.4,
        flashMultiplier: 1.0
    },
    heavy: {
        id: "heavy",
        name: "Heavy Laser",
        frequency: 0.0044,
        amplitude: 64,
        width: 9,
        fireRate: 0.42,
        strength: 5,
        color: "#ff4d7d",
        baseFrequency: 0.0044,
        baseAmplitude: 64,
        baseWidth: 9,
        baseFireRate: 0.42,
        baseStrength: 5,
        colors: ["#ff4d7d", "#ff7768", "#ffb06e", "#ff5f5f"],
        glowMultiplier: 2.2,
        flashMultiplier: 1.8
    }
}
